### PR TITLE
Optimize file size

### PR DESCRIPTION
**Pull request by emilbayes**
This optimizes the file size, and also allows for smaller minification.

### CODE REVIEW

**Comment by thunklife** [comment]
You are quick! :)

**Comment by emilbayes** [comment]
Haha, had it lined up :) Remember to bump the version and publish to npm. This should probably be a minor, right?

**Comment by thunklife** [comment]
Yeah, I'll just bump the minor. Thanks again.

**Comment by thunklife** [comment]
Let me know if anything is busted on npm, this is literally the only package I ever need to update and I always forget what I'm doing. :)

**Comment by emilbayes** [comment]
No worries! You got a god name and it's a great utility, that's why I keep contributing :b

**Pull request merged**
