### PR TITLE
add forgotten maybe-args in deps

### PR DESCRIPTION
**Pull request by iamstarkov**
it doesn't work from the start 'cause of forgotten deps. I added it

### CODE REVIEW

**Comment by thunklife** [comment]
Dang, I must have been asleep when I wrote this. :) Thanks again.

**Comment by iamstarkov** [comment]
No, it's fine. Thank you for lib. Also, is `fn-compose` already mature and can be bumped to 1.x?

**Comment by thunklife** [comment]
To be honest, this was something I wrote on a whim just to learn how to do it. I pushed it here and NPM just because. This is the most I've looked at it in months. If I were going to look to use a compose module in Production, it would be https://www.npmjs.com/package/lodash.compose. It's going to be far more stable, and far, far better tested.

I appreciate you taking time on this though.

**Comment by iamstarkov** [comment]
All I want is to use small module with zero dependencies and this module is good enough for this. Btw, thanks, I get you point. 

If we are talking about functional programming it's better to note [Ramda](https://www.npmjs.com/package/ramda).

**Comment by iamstarkov** [comment]
btw, please publish fixed version to npm

**Comment by thunklife** [comment]
Cool man. Bumped to 1.0.0 because I really have no reason not to.

**Comment by iamstarkov** [comment]
Thanks!

**Pull request merged**
